syntax = "proto3";

package message;

option csharp_namespace = "MessageService.Gpt";

message Role {
    string _id = 1;
    string name = 2;
    bool isActive = 3;
}

enum AccountType {
    LOCAL = 0;
    GOOGLE = 1;
    FACEBOOK = 2;
}

message Meta {
    int32 current = 1;
    int32 pageSize = 2;
    int32 pages = 3;
    int32 total = 4;
}

message MetaCursor {
    int32 pageSize = 1;
    bool hasMore = 2;
    string nextCreatedAt = 3;
    string nextId = 4;
}   

message User {
    string _id = 1;
    string name = 2;
    string email = 3;
    string image = 4;
    Role role = 5;
    AccountType accountType = 6;
}

message ActionItem {
    string label = 1;
    string route = 2;
}

message ChatRequest {
    optional string conversationId = 1;
    string prompt = 2;
    optional User user = 3;
}

message ChatResponse {
    string answer = 1;
    repeated ActionItem actions = 2;
    string data = 3;
    string error = 4;
    string qs = 5;
}

message AiConversationResponse {
    string id = 1;
    string userId = 2;
    string title = 3;
    string createdAt = 4;
    string updatedAt = 5;
}

message AiMessageResponse {
    string id = 1;
    string conversationId = 2;
    string messageRole = 3;
    string content = 4;
    string data = 5;
    string createdAt = 6;
    repeated ActionItem actions = 7;
    AiConversationResponse conversation = 8;
    string qs = 9;
}

message AiMessagePaginateRequest {
    int32 limit = 1;
    string conversationId = 2;
    string lastCreatedAt = 3;
    string lastId = 4;
}

message AiConversationPaginateRequest {
    int32 currentPage = 1;
    int32 limit = 2;
    string userId = 3;
}

message AiMessageListResponse {
    repeated AiMessageResponse result = 1;
    MetaCursor meta = 2;
}

message AiConversationListResponse {
    repeated AiConversationResponse result = 1;
    Meta meta = 2;
}

message QuickResponse {
    string message = 1;
}

message DeleteConversationByUserRequest {
    string userId = 1;
}

service GeminiService {
    rpc chat(ChatRequest) returns (ChatResponse);
}

service ChatEFService {
    rpc findAllMessage(AiMessagePaginateRequest) returns (AiMessageListResponse);
    rpc findAllConversation(AiConversationPaginateRequest) returns (AiConversationListResponse);
    rpc deleteConversationByUser(DeleteConversationByUserRequest) returns (QuickResponse);  
}